name: habitus_faith
description: App para llevar hábitos cristianos y fortalecer tu fe día a día.
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  uuid: ^4.5.1
  lottie: ^3.1.0
  sqflite: ^2.3.0
  path: ^1.9.0
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  shared_preferences: ^2.5.3
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  intl: ^0.20.2
  auto_size_text: ^3.0.0
  scrollable_positioned_list: ^0.3.8
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  firebase_messaging: ^15.1.5
  flutter_timezone: ^3.0.1
  permission_handler: ^11.3.1
  tflite_flutter: ^0.12.1
  http: ^1.2.0
  workmanager: ^0.8.0
  google_generative_ai: ^0.4.0
  flutter_dotenv: ^5.1.0
  synchronized: ^3.1.0
  logger: ^2.0.0
  fl_chart: ^0.69.0
  signature: ^5.4.1
  table_calendar: ^3.0.9
  string_similarity: ^2.0.0
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.13
  mocktail: ^1.0.4
  fake_cloud_firestore: ^3.0.3
  firebase_auth_mocks: ^0.14.1
  riverpod_test: ^0.1.9
  coverage: ^1.9.2
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  envied_generator: 1.1.1

dependency_overrides:
  vector_math: ^2.2.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/lottie/animation.json
    - assets/lottie/
    - assets/biblia/
    - assets/ml_models/predictor.tflite
    - assets/ml_models/scaler_params.json
    - assets/ml_models/model_metadata.json
    - assets/habit_templates_v2/
    - .env
  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
